import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MarketingLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <p className="ml-5">MarketingLayout</p>
        {children}
      </body>
    </html>
  );
};

export default MarketingLayout;
